### ISSUE TITLE
Suggestion of app to add to the list

### ISSUE THREAD

**Issue by marcelinohermida** [jrkerns/awesome-medphys#3]
Hi:
Awesome list! Thanks for compiling it. Thanks for including my scripts MUSIMAN. Maybe you can consider to include my Python scripts "PRIMO Watchdog", to automate Monte Carlo simulations with the PRIMO software. The scripts are available at:

https://github.com/marcelinohermida/PRIMO_WatchDog

both in source code, and as a release with an executable file.

Thanks and regards,

Marcelino Hermida

**Comment by jrkerns** [comment]
Hi Marcelino, feel free to make a pull request.

**Comment by marcelinohermida** [comment]
Done! Thanks

Marcelino





Dr. Marcelino Hermida López

Medical physicist |  Servei de Fisica i Protecció Radiològica

Hospital Universitari Vall d’Hebron

Vall d’Hebron Barcelona Hospital Campus



Passeig de la Vall d’Hebron, 119-129 | 08035 Barcelona | Tel. +34 93 274 6053

***@***.******@***.***> | www.vallhebron.com<https://www.vallhebron.com/ca>





Aquest missatge s’adreça exclusivament a la persona destinatària i pot contenir informació privilegiada o confidencial. Si no sou la persona destinatària indicada, us recordem que la utilització, divulgació i/o còpia sense autorització està prohibida en virtut de la legislació vigent. Si heu rebut aquest missatge per error, us demanem que ens ho feu saber immediatament per aquesta via i que el destruïu. Abans d’imprimir aquest correu, assegureu-vos que és realment necessari. Vall d’Hebron Barcelona Hospital Campus és un centre totalment lliure de fum.

Prohibit fumar a tot el recinte.

________________________________
De: James Kerns ***@***.***>
Enviado: lunes, 2 de septiembre de 2024 22:47
Para: jrkerns/awesome-medphys ***@***.***>
Cc: Hermida Lopez, Marcelino ***@***.***>; Author ***@***.***>
Asunto: Re: [jrkerns/awesome-medphys] Suggestion of app to add to the list (Issue #3)


Hi Marcelino, feel free to make a pull request.
